#!/usr/bin/env bash

# bar settings
yabai -m config status_bar                   off
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
yabai -m config status_bar_background_color  0xff202020
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip  I II III IV V VI VII VIII IX X
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_placement      inset
yabai -m config window_border_width          2
yabai -m config window_border_radius         -1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl  # was alt before, but this breaks copying from vim at the moment
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# window rules
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Preferences$" manage=off
yabai -m rule --add app="^Bitwarden$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Code42 CrashPlan$" manage=off
yabai -m rule --add app='IntelliJ IDEA' title='.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Charges|Tip*.|Rename*.|Preferences|Data Sources and Drivers|Project Structure|Inspect|Move.*|Extract.*|Export.*|Create.*' manage=off

if [[ "$(hostname)" == *"linkedin.biz"* ]]; then
  echo "loading work laptop specific..."
  yabai -m rule --add app="Outlook" display=2 space=7
  yabai -m rule --add app="^Slack$" display=2 space=7
  yabai -m rule --add app="Rambox" display=2 space=11
  yabai -m rule --add app="Messages" display=2 space=11
  yabai -m rule --add app="Spotify" display=3
  yabai -m rule --add app="Todoist" display=2 space=6
  yabai -m rule --add app="iTerm2" title="tower.*hotkey" manage=off
else
  echo "loading personal laptop specifics..."
  yabai -m rule --add app="Canary Mail" space=2
  yabai -m rule --add app="Todoist" space=6
  yabai -m rule --add app="Discord" space=7 # grid=6:6:1:1:3:3
  yabai -m rule --add app="Messages" space=11
  yabai -m rule --add app="iTerm2" title=".*hotkey" manage=off
fi



# make inactive windows transparent
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# update bitbar plugin with current space
yabai -m signal --add event=space_changed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_added action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_removed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_changed action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"
yabai -m signal --add event=display_moved action="open -gj 'bitbar://refreshPlugin?name=yabai.1d.sh'"

echo "yabai configuration loaded.."


